### ISSUE TITLE
Authentication success message

### ISSUE THREAD

**Issue by mikeapp** [yalelibrary/yul-dc-blacklight#1053]
**Story**

I think I saw this message after logging in with a local account:

![Image](https://github.com/user-attachments/assets/9c702c91-2605-4b90-95d0-8cc3252de541)

This is confusing if you did not log in via CAS.

**Acceptance**
- [x] Display a generic success message that does not mention CAS

**Comment by sshetenhelm** [comment]
Language: "Successfully logged in." or something like that is fine.

**Comment by jpengst** [comment]
PR: https://github.com/yalelibrary/yul-dc-blacklight/pull/1059

**Comment by K8Sewell** [comment]
Deployed to Test with release [v1.64.2](https://github.com/yalelibrary/yul-dc-blacklight/releases/tag/v1.64.2)

**Comment by K8Sewell** [comment]
On Test new messaging is present.  Will promote to UAT.

![Image](https://github.com/user-attachments/assets/aeee6a35-9acc-4b5e-81b6-baff14e88e66)

**Comment by sshetenhelm** [comment]
Looks good on UAT! Thank you, ready to close.
